### ISSUE TITLE
Multiple Sections (with multiple lines depending on session)

### ISSUE THREAD

**Issue by morgan-legal** [ashfurrow/Collection-View-in-a-Table-View-Cell#11]
Hi there,
Thank you very much for the tutorial! 
I do not have any issue with your work but trying to push it a bit more on some levels. I have trouble getting the tableView section in the collectionView. I have multiple sections and each of them do not have the same number of rows. 
For example (see picture bellow);
- Section 0: One row, Two collectionView cells (supposed to be one cell)
- Section 1: One row, Two collectionView cells
- Section 2: Two rows, Two collectionView cells on the first row and One cell on the second row (using flow layout delegate)
- ... there is a lot more...

<img width="313" alt="screen shot 2016-02-24 at 9 16 18 pm" src="https://cloud.githubusercontent.com/assets/11411520/13299583/0b7f9a0e-db3c-11e5-96de-bc6253cda5a3.png">

So, I would need the section index in the collectionView (numberOfItemsInSection) to set the appropriate number of cell. For some reason the "section" parameter of the function does not give me the right one. Any idea?

**Comment by ashfurrow** [comment]
Sounds like you're running into limitations using the tag property to indicate bo h the row and section the collection view is in. I would try subclassing UICollectionView and add an indexPath property and use that in place of the tag. Try it and let me know how it goes. I'm away right now but I'll try to take a look when I get back. 
-- 
Ash Furrow
https://ashfurrow.com/

**Comment by morgan-legal** [comment]
Thanks for the tip. Didn't manage to make it work yet. I'm still learning swift. 
So your idea is to create a class (TableViewCell.swift file);
`
class TableViewCell: UITableViewCell {
    @IBOutlet private weak var collectionView: CustomCollectionView!
}

class CustomCollectionView: UICollectionView {
    var indexPath: NSIndexPath?
    
     required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)!
    }
    
    override func awakeFromNib() {
        super.awakeFromNib()
    }
}

extension TableViewCell {

    func setCollectionViewDataSourceDelegate<D: protocol<UICollectionViewDataSource, UICollectionViewDelegate>>(dataSourceDelegate: D, forIndexPath indexPath: NSIndexPath) {

        collectionView.indexPath = indexPath
        collectionView.delegate = dataSourceDelegate
        collectionView.dataSource = dataSourceDelegate
        //collectionView.tag = row
        collectionView.setContentOffset(collectionView.contentOffset, animated:false) // Stops collection view if it was scrolling.
        collectionView.reloadData()
    }

    var collectionViewOffset: CGFloat {
        set {
            collectionView.contentOffset.x = newValue
        }

        get {
            return collectionView.contentOffset.x
        }
    }
}`

In the ViewController.swift file 
           
` let cell = tableView.dequeueReusableCellWithIdentifier("Cell", forIndexPath: indexPath) as! TableViewCell
            cell.setCollectionViewDataSourceDelegate(self, forIndexPath: indexPath)
            return cell`

But the problem is in the extension ViewController. The collectionView parameters for all the delegate and datasource methods do not have the "indexPath" property set in the subclass "CustomCollectionView". I'm sure i'm missing something pretty important part here but giving my current swift skills I cannot see what...

**Comment by ashfurrow** [comment]
OK, this is good, you're almost there. You now need to access the property when a cell is to be configured or selected, using conditional casts to the collection view subclass..

```swift
func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
    let cell = collectionView.dequeueReusableCellWithReuseIdentifier("Cell", forIndexPath: indexPath)

    if let customCollectionView = collectionView as? CustomCollectionView {
        cell.whatever = /* access data using customCollectionView.indexPath and indexPath */
    }

    return cell
}

func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {
    guard let customCollectionView = collectionView as? CustomCollectionView else { return }

    print("Collection view at index path \(customCollectionView.indexPath) selected inner index path of \(indexPath)")
}
```

Index paths are already a bit tricky, and we're using next index paths, so it's normal to have some trouble here. Keep and it and I'm sure you'll figure it out :+1:

**Comment by morgan-legal** [comment]
Awesome. Works like a charm. Thank you for your time and help!

**Comment by ashfurrow** [comment]
Gad you got it to work!

**Comment by akhilclement** [comment]
hi morgan, i'm getting error EXC_BAD_ACCESS at collectionView.indexPath = indexPath and collectionView.indexPath found nil...
