### ISSUE TITLE
Horizontal collectionview doesn't fill tableview cell

### ISSUE THREAD

**Issue by gkye** [ashfurrow/Collection-View-in-a-Table-View-Cell#17]
Hey Ash, thanks for the great tutorial!!!! :smile: 

Im currently attempting to add a horizontal `uicollectionview` within a tableview but the collectionview doesnt fill the tableview cell. I've set `heightForRowAtIndexPath` to `UITableViewAutomaticDimension` but that doesn't do much and the collectionview's cells are cut off if I set a hard coded value. I was wondering if there was a way to make the `uicollectionview` dynamically fill the tableview cell? I've also tried setting a `contentSize` variable which will later be equal to `collectionView.contentSize.height` that allows the collectionview to fill the cell but theres a lot of space (between the first section and where the collectionview starts in the second section)
**I've included some sheetshots below to further explain**

```swift
//section 2 of tableview cell
    var contentSize: CGFloat! = UITableViewAutomaticDimension

    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        if(indexPath.section == 0){
            if(indexPath.row == 0){
           //return irrelevant cells    
           }
        }else{
            let cell = tableView.dequeueReusableCellWithIdentifier("shotsCell")
            tableView.rowHeight = UITableViewAutomaticDimension
            tableView.estimatedRowHeight = 200
            return cell!
        }
    }
//heightForRowAtIndexPath
    override func tableView(tableView: UITableView, heightForRowAtIndexPath indexPath: NSIndexPath) -> CGFloat {
        if(indexPath.section == 0 && indexPath.row == 0){
            return 146
        }else{
            return UITableViewAutomaticDimension
     //            return contentSize
          }
    }
```
**Collectionview**

```swift 
  
    func collectionView(collectionView: UICollectionView, willDisplayCell cell: UICollectionViewCell, forItemAtIndexPath indexPath: NSIndexPath) {
        contentSize = collectionView.bounds.height
    }  
    func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
        return CGSize(width: collectionView.bounds.width / 2 - 2, height: 200)
    }
```

# With contentsize set
![](http://g.recordit.co/VSHJBOSV9d.gif)
# UITableViewAutomaticDimension
![](http://i.imgur.com/ug27FSc.png)

**Comment by ashfurrow** [comment]
Hmm, I've never used the automatic height sizing of UITableViewCell's. I don't really know how it works, but I think int requires autolayout constraints for the cell's subviews (in this case, the collection view). I would try adding the constraints to the cell in the storyboard and seeing if that helps.

**Comment by gkye** [comment]
Thanks, I was able to get the collection view cells to display as desired by adding a height constraint to the collectionview but it still doesn't fill the tableview. Do you have any suggestions? (I want to disable scroll on the embedded collectionview)

**Comment by ashfurrow** [comment]
Hmm, you mean it doesn't fill the cell horizontally? Maybe there's something weird with scroll views and constraints if their content size is larger than their size (i.e. if they scroll). I'm not sure what to do about that. However, to disable scrolling on the collection view, you should be able to just setting its `scrollingEnabled` property to `NO`. Good luck!
