### ISSUE TITLE
How to push my data to it's collection view?

### ISSUE THREAD

**Issue by dbaklanova** [ashfurrow/Collection-View-in-a-Table-View-Cell#18]
Oh, it was so useful tutorial.

I did not understand how to return cells by it's categories (my cells have categories :) ) to it's Collection View :(

 ```
   func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.dequeueReusableCellWithReuseIdentifier("BroadcastCell", forIndexPath: indexPath) as? BroadcastCell
        let broadcasts: [Broadcast] = self.broadcastInSection(collectionView.tag)
        let broadcast = broadcasts[indexPath.row]
        
        cell?.configureCell(broadcast)
        return cell!
    }
```

Now it looks like the same cells in every Collection View I have.

broadcastInSection(index) - filter my cells by category.index

How can I fix it?

**Comment by ashfurrow** [comment]
Hmm, if I had to guess I would bet that the `collectionView.tag` isn't being set, so it's always zero and always returns the same array. Can you add `print(collectionView.tag)` and see what happens?

**Comment by dbaklanova** [comment]
Yes 🙈 I've already checked it, and there were 0 😭 It is not set? I thought, I did everything from your tutorial ((( will check it now!

**Comment by ashfurrow** [comment]
They should be set in the table view delegate method, `willDisplayCell `: https://github.com/ashfurrow/Collection-View-in-a-Table-View-Cell/blob/ec5af131532c833557c128e2e0643de478e0b573/Table%20View%20in%20a%20Collection%20View/ViewController.swift#L19 and in `setCollectionViewDataSourceDelegate`: https://github.com/ashfurrow/Collection-View-in-a-Table-View-Cell/blob/ec5af131532c833557c128e2e0643de478e0b573/Table%20View%20in%20a%20Collection%20View/TableViewCell.swift#L15 Good luck, let me know how it goes!

**Comment by dbaklanova** [comment]
Thank you so much! 
Don't know what was a problem there, I'd to start a new project, and now it works good! 👍

**Comment by ashfurrow** [comment]
Awesome! Glad you got it to work. These kinds of problems happen to everyone 😄
