### ISSUE TITLE
getRandomData

### ISSUE THREAD

**Issue by vTrip** [ashfurrow/Collection-View-in-a-Table-View-Cell#2]

**Comment by ashfurrow** [comment]
Hey there! Did you find the method? It's tucked away in another swift file.

**Comment by vTrip** [comment]
I did, apologies for opening an issue I closed it as soon as I found it.

Regards,

Vince

**Comment by ashfurrow** [comment]
No apologies necessary! I'm glad you got it sorted out.

**Comment by vTrip** [comment]
Excellent tutorial by the way ! 

Regards,

Vince
