### ISSUE TITLE
Followed your approach but showing up the cells incompletely.

### ISSUE THREAD

**Issue by pradeepb28** [ashfurrow/Collection-View-in-a-Table-View-Cell#20]
in my current implementation I wanted to show only one cell on the screen it seems like i am able to see one cell with another cell half way through. How can i get rid off this stuff?

**Comment by pradeepb28** [comment]
Even in your tutorial if you look at the collection view cell, the last cell is cut off half.

**Comment by ashfurrow** [comment]
Thanks for opening an issue with your question. Could you post a screenshot showing the incorrect behaviour? The last cell looks okay from here (running Xcode 7.3).

<img width="423" alt="screen shot 2016-07-07 at 3 31 23 pm" src="https://cloud.githubusercontent.com/assets/498212/16666887/a03e7c12-4457-11e6-9dad-8e92b8b9c486.png">

UICollectionView has a very difficult time when cells are wider than the collection view themselves, you'll often see warnings printed in the console log about this when you get cells that large. A workaround could be to make the collection view slightly wider than the table view cell, I'd suggest experimenting to see what works for you.

**Comment by pradeepb28** [comment]
Oops I could have been clear ...I mean if you look at the second row and the cell is half displayed on the screen from right side? Is it possible to show only complete visible cells ?

**Comment by ashfurrow** [comment]
Ah, gotcha. Whether a cell is partially visible depends on the size of each cell and the space between the cells, both of which can be set as properties on the layout. Generally, you need to satisfy "width of the collection view = number of cells * width of cell + (number of cells + 1) * width of interitem spacing", let me know how it goes.

**Comment by ashfurrow** [comment]
So a width of 320 would be satisfied by 3 cells of 100 pts each and a separation of 5 pts.
