### ISSUE TITLE
How can I use this with remote json parsing ?

### ISSUE THREAD

**Issue by codeservis** [ashfurrow/Collection-View-in-a-Table-View-Cell#23]
How can I use this with remote json parsing ?

Thank you

**Comment by ashfurrow** [comment]
Hi there, using JSON parsing should be straightforward with this approach. The [model](https://github.com/ashfurrow/Collection-View-in-a-Table-View-Cell/blob/master/Table%20View%20in%20a%20Collection%20View/ViewController.swift#L5) would change to store your parsed JSON and the cells would need to change to display whatever data is in the JSON. [Here's a JSON parsing tutorial](https://www.raywenderlich.com/120442/swift-json-tutorial) that should get you started. Good luck!

**Comment by codeservis** [comment]
Thank you but I'm new in swift can you add json parsing into it ?  I think will be help many people I didn't find like your project with json parsing. 

Thank you !

**Comment by ashfurrow** [comment]
I think the tutorial is good if it teaches a core concept, and JSON parsing would really complicate things. And JSON parsing isn't something that's done one way, it could be done any way depending on the JSON, so adding it to the tutorial wouldn't be helpful for most readers. The JSON parsing tutorial I linked to should help you out. Good luck!
