### ISSUE TITLE
Scroll collection view cell in all row on scrolling anyone

### ISSUE THREAD

**Issue by anishparajuli555** [ashfurrow/Collection-View-in-a-Table-View-Cell#25]
Is there a way ,where i scroll the collection view on first row and make all the collection view cells of other row to scroll at that position?

**Comment by ashfurrow** [comment]
Hmm, hard to say. I don't know if I quite understand what you're looking for – could you describe it in more detail?

**Comment by anishparajuli555** [comment]
What i want to do is when user scrolls The cell in one row..I want all the the cells to scroll that position..Well i have been able to acheive what i want.But not as expected..

```
   func scrollViewDidScroll(scrollView: UIScrollView) {
        
        if scrollView.isKindOfClass(UICollectionView){
            tempContentOffSet = scrollView.contentOffset
        }
    }
  func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
                 
            if collectionView.contentOffset.x != tempContentOffSet.x {
                collectionView.contentOffset.x = tempContentOffSet.x
            }
    }

```
