### ISSUE TITLE
How to reload collectionView in UIViewController?

### ISSUE THREAD

**Issue by vlafiser** [ashfurrow/Collection-View-in-a-Table-View-Cell#26]
Thanks for your article firstly!

I'm using Firebase, but I can't figure out how to update `collectionView`, because the reference is just in the cell where I have the function with delegate etc.

Basically I'm fetching photos from Firebase on `viewDidLoad` and then user can add photo which means I need to update collectionView.

Do you know how to manage it please?

Thanks!
Vlasti

**Comment by vlafiser** [comment]
Oh, solution which works for me is here:

```
DataService.dateService.fetchPhotos((gallery)!){ (photo) in
    self.photos.append(photo)
    self.tableView.reloadData()
            
    let indexPath = NSIndexPath(forItem: 2, inSection: 0)
    let collectionViewIndexPath = NSIndexPath(forItem: (self.photos.count + 1), inSection: 0)
            
    let photoCell: DetailPhotoTableViewCell = self.tableView.dequeueReusableCellWithIdentifier("cell", forIndexPath: indexPath) as! DetailPhotoTableViewCell
    photoCell.configureCell()
    photoCell.setCollectionViewDataSourceDelegate(self, forRow: collectionViewIndexPath.row)
    photoCell.photosCollectionView.reloadData()
}
```

This code is in my `ViewController` in `viewDidLoad` and update my `collectionView` real-time by Firebase.

**Comment by ashfurrow** [comment]
Fab! Glad you got it sorted, and thanks for posting a follow-up!
