### ISSUE TITLE
when scroll collection view will crash due to Index out of range

### ISSUE THREAD

**Issue by xuyang1993** [ashfurrow/Collection-View-in-a-Table-View-Cell#30]
Hi, i have an question: if the collection view cell numberOfItemsInSection are different, and when i scroll collection view  will crash due to Index out of range.
I found the problem that when i scroll the tableview the collection view cell index path updated to the bottom one, but the collection view i scrolled is top one and it does't remember the numberOfItemsInSection, so it will crash due to Index out of range .

ps: it can scroll only when that table cell at the bottom, coz its numberOfItemsInSection is correspond won't cause Index out of range.
And each of my collection view numberOfItemsInSection is different.

Do you have any idea how to solve this problem?
Thanks

**Comment by ashfurrow** [comment]
I'm not sure I understand the question, can you record a video explaining the issue maybe?

**Comment by ashfurrow** [comment]
Or maybe you could upload the Xcode project with the problem so I can take a look at the code?

**Comment by xuyang1993** [comment]
@ashfurrow  Hi sir, i uploaded to Git and can u help me check? 
It's in MenuCategoryViewController.swift 
Thank you

**Comment by ashfurrow** [comment]
Hey there, I'd be happy to look! I'm travelling this week but will take a look when I get home.

**Comment by xuyang1993** [comment]
@ashfurrow  thanks sir :)

**Comment by ashfurrow** [comment]
This is a pretty complex application, not really sure where to start. I don't normally consult on full projects; I apologize for the misunderstanding but I'm not able to help you on this. I would suggest stripping the part of the app down to the minimal collection view and trying to reproduce the bug, and debug it that way. Good luck!
