### ISSUE TITLE
deleagte and datasource are nil

### ISSUE THREAD

**Issue by adavan2107** [ashfurrow/Collection-View-in-a-Table-View-Cell#36]
fatal error: unexpectedly found nil while unwrapping an Optional value

deleagte and datasource are nil please help in advance

```swift
func setCollectionViewDataSourceDelegate<D: UICollectionViewDataSource & UICollectionViewDelegate>(_ dataSourceDelegate: D, forRow row: Int) {
        
        postsocialcollectionview.delegate   = dataSourceDelegate
        postsocialcollectionview.dataSource = dataSourceDelegate
        postsocialcollectionview.tag        = row
        postsocialcollectionview.reloadData()
        
    }
```

**Comment by ashfurrow** [comment]
I can't really say without looking at the larger app, sorry! Here's what I would do: find where this function is called from and debug why the `dataSourceDelegate` is `nil`. There's probably an implicitly-unwrapped optional somewhere. Good luck!
