### ISSUE TITLE
Custom collectionview cell content

### ISSUE THREAD

**Issue by dumpy-dev** [ashfurrow/Collection-View-in-a-Table-View-Cell#41]
Such a useful tutorial. However, I am just unclear about how to set up custom content within the collection view cell, such as a UIImage or Label - where should the outlets be created to allow access to their properties within

func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {}

Hope that question makes sense... I'm probably just misunderstanding something basic!
Thank you and thanks again for the tutorial!

**Comment by dumpy-dev** [comment]
Problem solved!

**Comment by ashfurrow** [comment]
Great! Glad you got it figured out.
