### ISSUE TITLE
collection view datasource mthod not getting called

### ISSUE THREAD

**Issue by ajthmhn** [ashfurrow/Collection-View-in-a-Table-View-Cell#42]
Hi,

I have more than one type of cell in a table view.One of the types is a collection view rest are not. In that case, I used the code u referred but the data source methods of collection view are not getting called.

Hope you understand what I am trying to say and expect a solution from your side

thank you

**Comment by ashfurrow** [comment]
Hey, sorry to hear you're having trouble. This is a repo for a tutorial, not a place where I debug your problems for you. Double-check your code and list your assumptions, then test them. You can do this, good luck.

**Comment by MarcSteven** [comment]
@ashfurrow great tips for debugging,long time no see @ashfurrow  What are you doing now?

**Comment by ashfurrow** [comment]
@MarcSteven thanks – I've been pretty busy at work and moving (within NYC, which has been difficult). Things starting to settle back down but still more to do than hours in a day 😅

**Comment by MarcSteven** [comment]
That make sense I reviewed your status via twitter ,thank for your sharing ,learn more from you .Welcome to China next time and then give more developers a great talk about software engineer. @ashfurrow Good luck to you !!
