### ISSUE TITLE
Understanding Logic

### ISSUE THREAD

**Issue by juniorProgrammer** [ashfurrow/Collection-View-in-a-Table-View-Cell#5]
So I understand that you created a UICollectionView using IB. I was wondering if I was creating it programmatically. Because you have this delegate/datasource function and some Constraint func inside the TableviewCell. I'm trying to figure it out so i can understand it more so I can manipulate it.

**Comment by ashfurrow** [comment]
Did you get this figured out?

**Comment by juniorProgrammer** [comment]
Yeah I kind of did. I was doing before was assigning the delegate and data source to my tablecell file instead of making my table view controller to a collection view delegate and data source. I was trying to figure you tablecell file and why did you create a delegate/datasource function in that file

**Comment by ashfurrow** [comment]
Gotcha – I've got an [older, code-only example](https://github.com/AshFurrow/AFTabledCollectionView) that's in ObjC. Let me know if I can clarify anything.
